name: Bug Report
description: Report a bug in Parcel.NET
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Call `...`
        2. With parameters `...`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include any error messages or exception stack traces.
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which Parcel.NET package is affected?
      options:
        - Parcel.NET.Abstractions
        - Parcel.NET.Dhl
        - Parcel.NET.Dhl.Shipping
        - Parcel.NET.Dhl.Tracking
        - Parcel.NET.Dhl.UnifiedTracking
        - Parcel.NET.Dhl.Pickup
        - Parcel.NET.Dhl.Returns
        - Parcel.NET.Dhl.Internetmarke
        - Parcel.NET.Dhl.LocationFinder
        - Parcel.NET.GoExpress
        - Parcel.NET.GoExpress.Shipping
        - Parcel.NET.GoExpress.Tracking
        - Other
    validations:
      required: true

  - type: dropdown
    id: carrier
    attributes:
      label: Carrier
      description: Which carrier is involved?
      options:
        - DHL
        - GO! Express
        - Multiple / Not applicable
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      options:
        - .NET 10
        - .NET 9
        - .NET 8
        - Other
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: The version of the Parcel.NET package you're using.
      placeholder: e.g. 0.1.0-alpha
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (OS, configuration, etc.).
